# This is a basic workflow to help you get started with Actions

name: CI
on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - uses: actions/checkout@v2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
      - name: deploy vnet
        uses: azure/arm-deploy@v1
        if: ${{ false }}
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: "learning"
          template: ./vnet.bicep
          deploymentMode: Incremental
          parameters: ./vnet-params.json
          failOnStdErr: false
      - name: deploy ubuntu vm
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: "learning"
          template: ./windowsvm.bicep
          deploymentMode: Incremental
          parameters: adminPassword=${{ secrets.ADMIN_PASSWORD }}
          failOnStdErr: false

